# Generated by Django 4.2 on 2023-04-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_lot_comment_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
