# Generated by Django 4.2 on 2023-04-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_lot_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='lot',
            name='category',
        ),
        migrations.AddField(
            model_name='lot',
            name='category',
            field=models.ManyToManyField(to='auctions.category'),
        ),
    ]
