# Generated by Django 4.2 on 2023-04-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_category_remove_lot_category_lot_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
